# Generated by Django 5.1.4 on 2025-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='realtor',
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_hot_selling',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='ddata/properties/%Y/%m/%d/'),
        ),
    ]
