# Generated by Django 5.1.4 on 2025-08-04 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0003_alter_property_bathrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='ddata/agents/')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='FeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='primary', max_length=20)),
                ('properties', models.ManyToManyField(blank=True, related_name='tags', to='squarebox.property')),
            ],
            options={
                'db_table': 'feature_tag',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='squarebox.property')),
            ],
            options={
                'db_table': 'lead',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'property_type',
            },
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='datamode',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='squarebox.property'),
        ),
        migrations.AlterModelTable(
            name='propertyimage',
            table='property_image',
        ),
    ]
