# Generated by Django 5.1.4 on 2025-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0004_agent_featuretag_lead_propertytype_delete_realtor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('INDEPENDENT_HOUSE', 'Independent House'), ('PLOT', 'Plot / Land'), ('COMMERCIAL', 'Commercial Property'), ('STUDIO', 'Studio Apartment')], max_length=100),
        ),
    ]
