# Generated by Django 5.1.4 on 2025-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0006_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(help_text='Select the type of property, e.g., House, Villa, Plot/Land, Apartment', max_length=100),
        ),
    ]
