# Generated by Django 5.1.4 on 2025-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0007_alter_propertytype_name'),
    ]

    operations = [
    migrations.AddField(
        model_name='propertytype',
        name='created_by',
        field=models.CharField(default='system', max_length=8),  # Replace 1 with appropriate default
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='propertytype',
        name='created_on',
        field=models.DateTimeField(auto_now_add=True),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='propertytype',
        name='datamode',
        field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20),
    ),
    migrations.AddField(
        model_name='propertytype',
        name='updated_by',
        field=models.CharField(default='system', max_length=8),  # Replace 1 with appropriate default
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='propertytype',
        name='updated_on',
        field=models.DateTimeField(auto_now=True),
    ),
]
