# Generated by Django 5.1.4 on 2025-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0008_propertytype_created_by_propertytype_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.CharField(default='admin', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='datamode',
            field=models.CharField(
                choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')],
                default='A',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(default='default_location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_by',
            field=models.CharField(default='admin', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(
                choices=[
                    ('APARTMENT', 'Apartment'),
                    ('VILLA', 'Villa'),
                    ('INDEPENDENT_HOUSE', 'Independent House'),
                    ('PLOT', 'Plot / Land'),
                    ('COMMERCIAL', 'Commercial Property'),
                    ('STUDIO', 'Studio Apartment'),
                ],
                help_text='Select the type of property, e.g., House, Villa, Plot/Land, Apartment',
                max_length=100,
            ),
        ),
    ]