# Generated by Django 5.1.4 on 2025-08-08 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0009_lead_created_by_lead_created_on_lead_datamode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='created_by',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='datamode',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_by',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
