# Generated by Django 5.1.4 on 2025-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0011_maintenancerequest_delete_featuretag'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='datamode',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_by',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
