# Generated by Django 4.2.5 on 2025-08-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0012_maintenancerequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
