# Generated by Django 4.2.5 on 2025-08-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0013_lead_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='property',
        ),
    ]
