# Generated by Django 5.1.4 on 2025-08-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0014_remove_lead_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10, verbose_name='Listing Type'),
        ),
    ]
