# Generated by Django 5.1.4 on 2025-08-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0016_remove_property_bathrooms_remove_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='datamode',
        ),
    ]
