# Generated by Django 5.1.4 on 2025-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0018_remove_property_datamode_maintenancerequest_datamode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='datamode',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactivated'), ('D', 'Deleted')], default='A', max_length=20),
        ),
    ]
