# Generated by Django 5.1.4 on 2025-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squarebox', '0019_property_datamode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='builtup_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='commercial_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='conference_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='corner_unit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='end_unit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='facing_direction',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floor_height',
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnishing_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garden_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hoa_fee',
        ),
        migrations.RemoveField(
            model_name='property',
            name='loading_capacity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='office_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='parking_capacity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='plot_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='plot_length',
        ),
        migrations.RemoveField(
            model_name='property',
            name='plot_width',
        ),
        migrations.RemoveField(
            model_name='property',
            name='reception_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='units_in_complex',
        ),
        migrations.RemoveField(
            model_name='property',
            name='water_availability',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
